### ISSUE TITLE
Can you refer to Fileman's "global search' feature from pull-down menu?

### ISSUE THREAD

**Issue by ichthyosaurus** [ichthyosaurus/harbour-file-browser#32]
Can you refer to Fileman's "global search' feature from pull-down menu?

(@dashinfantry here: https://github.com/ichthyosaurus/harbour-file-browser/pull/28#issuecomment-773613125)

**Comment by ichthyosaurus** [comment]
Sadly, Fileman has been deleted from Openrepos and Bitbucket. But what feature do you mean exactly? File Browser already supports searching for files/folders from the pull-down menu. You can change the default action that happens when you press the "enter" key in the settings (swipe right twice -> view and behavior -> default filter action -> recursive search). The search will start in the current directory, so you'll have to switch to "/" to search "globally".

**Comment by dashinfantry** [comment]
Can you make 'global serach' easier?it is still on github https://github.com/Xray1870/harbour-fileman/releases/tag/v1.2-release1


 
---Original---

**Comment by dashinfantry** [comment]
One pull-down option to'g global search'？Or click top bar twice to open'global serach'?


 
---Original---

**Comment by ichthyosaurus** [comment]
Oh, I didn't know they had their code on Github; thanks for the link.

Searching is already very simple:

1. You can scroll to the bottom and choose "Search" from the bottom pulley menu.

2. Directly from the filter line:

![pic-05](https://user-images.githubusercontent.com/33604595/106959119-27482f80-6732-11eb-97b1-86d3120aea27.png)

Pull down, enter your text, press search, be happy.

You can optionally configure that you can press the "enter" key to start immediately:

![pic-06](https://user-images.githubusercontent.com/33604595/106959215-4c3ca280-6732-11eb-8e0b-62b278288f66.png)

But that's not necessary.

The "filter line" filters the current view if you enter text and just close the menu without starting a search.

**Comment by ichthyosaurus** [comment]
I created a new feedback thread in the forums (here: https://forum.sailfishos.org/t/file-browser-support-and-feedback-thread/4566). Let's move the discussion there :).
